#!/usr/bin/env bash
# Generates THIRD-PARTY-LICENSES.md listing every Rust dependency's name,
# version, license expression, and repository. Requires `cargo-license`
# (installed in CI via `cargo install cargo-license --locked`).
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="${1:-$repo_root/THIRD-PARTY-LICENSES.md}"

if ! command -v cargo-license >/dev/null 2>&1; then
  echo "error: cargo-license not found on PATH (cargo install cargo-license --locked)" >&2
  exit 1
fi

# windows-latest's bash does not always alias python3; fall back to python.
if command -v python3 >/dev/null 2>&1; then
  PY=python3
elif command -v python >/dev/null 2>&1; then
  PY=python
else
  echo "error: no python3/python found on PATH" >&2
  exit 1
fi

cd "$repo_root"

{
  echo "# Third-Party Licenses"
  echo
  echo "Generated by \`packaging/generate-third-party-licenses.sh\` from"
  echo "\`cargo license --json --avoid-dev-deps\`. Regenerated for every release;"
  echo "do not hand-edit."
  echo
  echo "| Crate | Version | License | Repository |"
  echo "|---|---|---|---|"
} > "$out"

cargo license --json --avoid-dev-deps | "$PY" -c '
import json, sys

entries = json.load(sys.stdin)
for e in sorted(entries, key=lambda x: x["name"].lower()):
    name = e.get("name", "")
    version = e.get("version", "")
    license = (e.get("license") or "UNKNOWN").replace("|", ", ")
    repo = e.get("repository") or ""
    print(f"| {name} | {version} | {license} | {repo} |")
' >> "$out"

echo "Wrote $out"
