#!/usr/bin/env bash
# Generates THIRD-PARTY-LICENSES.md: every Rust dependency grouped by
# license, with the full license text bundled (not just an SPDX id), per
# Apache-2.0 redistribution obligations for permissively-licensed
# dependencies. Requires `cargo-about` (installed in CI via
# `cargo install cargo-about --locked --features cli`) and `about.toml`
# at the repo root, which is also the enforcement point: an unrecognized
# license in the dependency tree fails this script instead of shipping
# silently.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="${1:-$repo_root/THIRD-PARTY-LICENSES.md}"

if ! command -v cargo-about >/dev/null 2>&1; then
  echo "error: cargo-about not found on PATH (cargo install cargo-about --locked --features cli)" >&2
  exit 1
fi

# windows-latest's bash does not always alias python3; fall back to python.
if command -v python3 >/dev/null 2>&1; then
  PY=python3
elif command -v python >/dev/null 2>&1; then
  PY=python
else
  echo "error: no python3/python found on PATH" >&2
  exit 1
fi

cd "$repo_root"

cargo about generate --format json --workspace --fail | "$PY" -c '
import json, sys

data = json.load(sys.stdin)

lines = [
    "# Third-Party Licenses",
    "",
    "Generated by `packaging/generate-third-party-licenses.sh` from "
    "`cargo about generate --format json`. Regenerated for every release; "
    "do not hand-edit.",
    "",
    "## Summary",
    "",
    "| Crate | Version | License | Repository |",
    "|---|---|---|---|",
]

crate_rows = []
for lic in data["licenses"]:
    for entry in lic["used_by"]:
        c = entry["crate"]
        repo = c.get("repository") or ""
        crate_rows.append((c["name"], c["version"], lic["name"], repo))

for name, version, license, repo in sorted(crate_rows, key=lambda r: r[0].lower()):
    lines.append(f"| {name} | {version} | {license} | {repo} |")

lines += ["", "## Full License Texts", ""]

for lic in sorted(data["licenses"], key=lambda l: l["name"].lower()):
    crates = ", ".join(
        "{} {}".format(e["crate"]["name"], e["crate"]["version"]) for e in lic["used_by"]
    )
    lines.append("### " + lic["name"])
    lines.append("")
    lines.append(f"Used by: {crates}")
    lines.append("")
    lines.append("```")
    lines.append(lic["text"].strip())
    lines.append("```")
    lines.append("")

print("\n".join(lines))
' > "$out"

echo "Wrote $out"
